config/routes.rb
LeapsAndBounds::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :student_guardians

  get 'homepage/index'

  resources :report
  get :test, :to => 'reports#subject'

  resources :homepage
  root to: 'homepage#index'

  resources :student_teachers

  resources :teachers

  resources :subject_grade_levels

  resources :student_subject_grade_levels

  resources :teacher_subject_grade_levels

  resources :medical_issues

  resources :sign_in_outs

  resources :emergency_contacts

  resources :guardians

  resources :students

  resources :sign_form

  get 'system_time' => 'application#system_time'

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :medical_issues, :dependent => :delete_all
  has_many :student_teachers, :dependent => :delete_all
  has_many :teachers, through: :student_teachers
  has_many :student_guardians, :dependent => :delete_all
  has_many :guardians, through: :student_guardians
  has_many :student_subject_grade_levels, :dependent => :delete_all
  has_many :subject_grade_levels, through: :student_subject_grade_levels
  has_many :sign_in_outs, :dependent => :delete_all
  has_many :emergency_contacts, :dependent => :delete_all



  mount_uploader :contract, ContractUploader


  def self.search(query)
    where("first_name like ? or last_name like ? or email like ?", "%#{query}%","%#{query}%","%#{query}%")
  end

  #This method combines the first, middle, & last name unless there's no middle name then it's just first & last name
  def full_name
    if self.middle_name == nil
      self.first_name + ' ' + self.last_name
    else
      self.first_name + ' ' + self.middle_name + ' ' + self.last_name
    end
  end

  #Checks if the value is either nil or a blank string
  validates :sex, :birth_date, :presence => true

  #Specifies length constraints
  validates :first_name, :last_name, :tutoring_hours, :address1, :city, :state, :zip_code, :length =>
      {
          :minimum   => 2,
          :maximum   => 128,
          :too_short => ": %{count} characters is the minimum allowed",
          :too_long  => ": %{count} characters is the minimum allowed"
      }

  validates :primary_phone, :length =>
      {
          :minimum   => 2,
          :maximum   => 20,
          :too_short => ": %{count} characters is the minimum allowed",
          :too_long  => ": %{count} characters is the minimum allowed"
      }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    if params[:search]
      @students = Student.search(params[:search]).order("created_at DESC")
    else
      @students = Student.page(params[:page]).per(10)
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text "Hello World"
        send_data pdf.render, filename: "Student_#{@student}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :middle_name, :last_name, :birth_date, :sex, :tutoring_hours, :primary_phone, :secondary_phone, :email, :address1, :address2, :city, :state, :zip_code, :school_name, :contract)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student, class: 'form-horizontal', :html => {:multipart => true}) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, placeholder: "Type in First Name"%>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name, placeholder: "Type in Middle Name (Optional)" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, placeholder: "Type in Last Name" %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br>
    <%= f.date_select :birth_date, start_year: 1920 %>
  </div>
  <div class="field">
    <%= f.label :sex %>:</br>
    <%= f.label :sex, "Male", :value=> "Male" %>
    <%= f.radio_button :sex, "Male"%>
    <%= f.label :sex, "Female", :value=> "Female" %>
    <%= f.radio_button :sex, "Female"%>
  </div>
  <div class="field">
    <%= f.label :tutoring_hours %><br>
    <%= f.text_field :tutoring_hours, placeholder: "Type the amount of Tutoring Hours" %>
  </div>
  <div class="field">
    <%= f.label :primary_phone %><br>
    <%= f.text_field :primary_phone, placeholder: "e.g. 713-369-3024" %>
  </div>
  <div class="field">
    <%= f.label :secondary_phone %><br>
    <%= f.text_field :secondary_phone, placeholder: "e.g. 713-369-3024 (Optional)" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, placeholder: "Type in Email" %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1, placeholder: "Type in Street Address 1" %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2, placeholder: "Type in Street Address 2 (Optional)" %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city, placeholder: "Type in City" %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state, placeholder: "Type in State" %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code, placeholder: "Type in Zip Code" %>
  </div>
  <div class="field">
    <%= f.label :school_name %><br>
    <%= f.text_field :school_name, placeholder: "Type in name of school where student attends" %>
  </div>
    <hr/>
  <div class="field">
    <%= f.label :contract %>
    <%= f.file_field :contract %>
  </div>
<hr/>
  <div class="actions">
    <%= f.submit "Add", class: 'btn btn-success btn-small' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>
<center>
<%= render 'form' %>
</center>
<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Student Records</h1>
<%= form_tag(students_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Students" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>School</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.full_name, student %></td>
        <td><%= student.email %></td>
        <td><%= student.primary_phone %></td>
        <td><%= student.school_name %></td>
        <!--<td><%= link_to 'Show', student, class:'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class:'btn btn-xs btn-default'  %></td>-->
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<center>
<% if not params[:search] %>
    <%= will_paginate @students %>
<% end %>
<br>
 <table>
  <tr>
    <td>
      <%= link_to 'New Student', new_student_path, class:'btn btn-s btn-default'  %>
      <%= link_to 'Back To Home', homepage_index_path, class:'btn btn-s btn-default' %>
    </td>
  </tr>
</table></center>
<br>

app/views/students/new.html.erb
<h1>New Student</h1>
<center>
<%= render 'form' %>
</center>
<table class="table">
  <tr>
    <td><br>
      <%= link_to 'Back', request.referer %>
    </td>
  </tr>
</table>

app/views/students/show.html.erb
<h1>Student Record</h1>


  <div class="box">
    <h4 class="select">Student Information</h4>
    <table class="table">
    <thead>
    <th>Full Name:</th>
    <th>Sex:</th>
    <th>Birth date:</th>
    <th>Email:</th>
    <th></th>
    </thead>
    <tbody>
    <tr>
      <td><%= @student.full_name %></td>
      <td><%= @student.sex %></td>
      <td><%= @student.birth_date %></td>
      <td><%= @student.email %></td>
    </tr>
    </tbody>
  </table>
</div>

  <div class="box">
    <h4 class="select">Medical Information</h4>
    <table class="table">
      <thead>
      <th>Allergy and Medication:</th>
      </thead>
      <tbody>
      <tr>
        <td><% @student.medical_issues.each do |mi| %>
            <%= link_to mi.description, medical_issue_path(mi.id) %>
              <% if params[:allow_delete] %>
                <%= link_to 'Remove', medical_issue_path(mi), :method => :delete, class:'btn btn-xs btn-danger' %>
              <% end %>
          <br><% end %>
          <br/><%= link_to 'Add', "/medical_issues/new?student_id=#{@student.id}", class:'btn btn-xs btn-default' %></td>
      </tr>
      </tbody>
    </table>
  </div>

<div class="box">
  <h4 class="select">Guardian Profile</h4>
  <table class="table">
    <thead>
    <th>Guardian(s):</th>
    </thead>
    <tbody>
    <tr>
      <td><% @student.student_guardians.each do |ec| %>
            <%= link_to Guardian.find(ec.guardian_id).full_name, guardian_path(ec.guardian_id) %>
            <% if params[:allow_delete] %>
                <%= link_to 'Remove', student_guardian_path(ec), :method => :delete, class:'btn btn-xs btn-danger' %>
            <% end %>
            <br><% end %>
        <br/><%= link_to 'Add', "/student_guardians/new?student_id=#{@student.id}", class:'btn btn-xs btn-default' %></td>
    </tr>
    </tbody>
  </table>
</div>

  <div class="box">
    <h4 class="select">Contact Information</h4>
    <table class="table">
      <thead>
      <th>Primary Phone:</th>
      <th>Address 1:</th>
      <th>Address 2:</th>
      <th>City:</th>
      <th>State:</th>
      <th>Zip Code:</th>
      <th>Emergency Contact(s):</th>
      </thead>
      <tbody>
      <tr>
        <td><%= @student.primary_phone %></td>
        <td><%= @student.address1 %></td>
        <td><%= @student.address2 %></td>
        <td><%= @student.city %></td>
        <td><%= @student.state %></td>
        <td><%= @student.zip_code %></td>
        <td><% @student.emergency_contacts.each do |sg| %>
              <%= link_to sg.full_name, emergency_contact_path(sg.id) %><br/>
              <% if params[:allow_delete] %>
                  <%= link_to 'Remove', emergency_contact_path(sg), :method => :delete, class:'btn btn-xs btn-danger' %>
              <% end %>
          <% end %><br/><%= link_to 'Add', "/emergency_contacts/new?student_id=#{@student.id}", class:'btn btn-xs btn-default' %></td>
      </tr>
      </tbody>
    </table>
  </div>

<div class="box">
  <h4 class="select">Tutoring Information</h4>
  <table class="table">
    <thead>
    <th>School Name:</th>
    <th>Tutoring Hours:</th>
    <th>Teacher(s):</th>
    <th>Subject(s):</th>
    </thead>
    <tbody>
    <tr>
      <td><%= @student.school_name %></td>
      <td><%= @student.tutoring_hours %></td>
      <td><% @student.student_teachers.each do |st| %>
          <%= link_to st.teacher.full_name, teacher_path(st.teacher_id) %>
          <% if params[:allow_delete] %>
                <%= link_to 'Remove', student_teacher_path(st), :method => :delete, class:'btn btn-xs btn-danger' %>
          <% end %>
            <br><% end %>
      <br/><%= link_to 'Add', "/student_teachers/new?student_id=#{@student.id}", class:'btn btn-xs btn-default' %>
    </td>
      <td><% @student.student_subject_grade_levels.each do |sgl| %>
            <%= link_to sgl.subject_grade_level.name, subject_grade_level_path(sgl.id) %>
            <% if params[:allow_delete] %>
                <%= link_to 'Remove', student_subject_grade_level_path(sgl), :method => :delete, class:'btn btn-xs btn-danger' %>
            <% end %>
            <br><% end %>
        <br/><%= link_to 'Add', "/student_subject_grade_levels/new?student_id=#{@student.id}", class:'btn btn-xs btn-default' %>

    </tr>
    </tbody>
  </table>
</div>

<div class="box">
  <h4 class="select">Student Contract</h4>
  <table class="table">
    <tr>
        <td><br/><a href="<%= @student.contract %>" class="btn btn-primary btn-large">Download</a></a><br/></td>
    </tr>
    </tbody>
  </table>
</div>
<br>
<br>

<center><table class="table">
  <tr>
    <td>
        <%= link_to 'Edit', edit_student_path(@student), class:'btn btn-xs btn-default' %>
      <% if params[:allow_delete] %>
          <%= link_to 'Hide Remove Attributes', '?', class:'btn btn-xs btn-default' %>
      <% else %>
          <%= link_to 'Show Remove Attributes', '?allow_delete=1', class:'btn btn-xs btn-danger' %>
      <% end %>
        <%= link_to 'Back', students_path, class:'btn btn-xs btn-default' %>
    </td>
</tr>
</table></center>
<br>