config/routes.rb
LeapsAndBounds::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :student_guardians

  get 'homepage/index'

  resources :report
  get :test, :to => 'reports#subject'

  resources :homepage
  root to: 'homepage#index'

  resources :student_teachers

  resources :teachers

  resources :subject_grade_levels

  resources :student_subject_grade_levels

  resources :teacher_subject_grade_levels

  resources :medical_issues

  resources :sign_in_outs

  resources :emergency_contacts

  resources :guardians

  resources :students

  resources :sign_form

  get 'system_time' => 'application#system_time'

end

app/models/medical_issue.rb
class MedicalIssue < ActiveRecord::Base
  belongs_to :student

  #Checks if the value is either nil or a blank string
  validates :description, :presence => true

  #Validates associations with other models
  validates_associated :student

end

app/controllers/medical_issues_controller.rb
class MedicalIssuesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_medical_issue, only: [:show, :edit, :update, :destroy]

  # GET /medical_issues
  # GET /medical_issues.json
  def index
    @medical_issues = MedicalIssue.page(params[:page]).per(10)
  end

  # GET /medical_issues/1
  # GET /medical_issues/1.json
  def show
  end

  # GET /medical_issues/new
  def new
    @medical_issue = MedicalIssue.new
  end

  # GET /medical_issues/1/edit
  def edit
  end

  # POST /medical_issues
  # POST /medical_issues.json
  def create
    @medical_issue = MedicalIssue.new(medical_issue_params)

    respond_to do |format|
      if @medical_issue.save
        format.html { redirect_to @medical_issue, notice: 'Medical issue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medical_issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @medical_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medical_issues/1
  # PATCH/PUT /medical_issues/1.json
  def update
    respond_to do |format|
      if @medical_issue.update(medical_issue_params)
        format.html { redirect_to @medical_issue, notice: 'Medical issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medical_issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medical_issues/1
  # DELETE /medical_issues/1.json
  def destroy
    @medical_issue.destroy
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medical_issue
      @medical_issue = MedicalIssue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medical_issue_params
      params.require(:medical_issue).permit(:issue_type, :description, :notes, :student_id)
    end
end

app/helpers/medical_issues_helper.rb
module MedicalIssuesHelper
end

app/views/medical_issues/_form.html.erb
<%= form_for(@medical_issue) do |f| %>
  <% if @medical_issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medical_issue.errors.count, "error") %> prohibited this medical_issue from being saved:</h2>

      <ul>
      <% @medical_issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue_type %><br>
    <%= f.select(:issue_type, ['Allergy','Medication','Medical Hx']) %>

  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :size=>'50'%>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, :size=>'50x10' %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <% if params[:student_id] %>
        <%= f.collection_select(:student_id, Student.all, :id, :full_name, :selected => params[:student_id]) %>
    <% else %>
        <%= f.collection_select(:student_id, Student.all, :id, :full_name) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "Add", class: 'btn btn-success btn-small' %>
  </div>
<% end %>

app/views/medical_issues/edit.html.erb
<h1>Editing medical_issue</h1>
<center>
<%= render 'form' %>
</center>
<%= link_to 'Show', @medical_issue %> |
<%= link_to 'Back', medical_issues_path %>

app/views/medical_issues/index.html.erb
<h1>Medical Records</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Issue</th>
      <th>Type</th>
      <th>Student</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medical_issues.each do |medical_issue| %>
      <tr>
        <td><%= link_to medical_issue.description, medical_issue %></td>
        <td><%= medical_issue.issue_type %></td>
        <td><%= Student.find(medical_issue.student_id).full_name %></td>
        <!--<td><%= link_to 'Show', medical_issue, class:'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Edit', edit_medical_issue_path(medical_issue), class:'btn btn-xs btn-default' %></td>
        --><td><%= link_to 'Destroy', medical_issue, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @medical_issues %>
<br>

<center> <table>
  <tr>
    <td>
<%= link_to 'New Medical Issue', new_medical_issue_path, class:'btn btn-s btn-default' %>
<%= link_to 'Back To Home', homepage_index_path, class:'btn btn-s btn-default' %>
    </td>
  </tr>
</table></center>

<br>

app/views/medical_issues/new.html.erb
<h1>New Medical Issue</h1>

<center>
<%= render 'form' %>
</center>
<br>
<table class="table">
  <tr>
    <td><br>
      <%= link_to 'Back', request.referer %>
    </td>
  </tr>
</table>

app/views/medical_issues/show.html.erb
<h1>Medical Record</h1>


<center>
<div class="box">
  <h4 class="select">Student Information</h4>
  <table class="table">
    <thead>
    <th>Issue Type:</th>
    <th>Description:</th>
    <th>Notes:</th>
    <th>Student:</th>
    </thead>
    <tbody>
    <tr>
      <td><%= @medical_issue.issue_type %></td>
      <td><%= @medical_issue.description %></td>
      <td><%= @medical_issue.notes %></td>
      <td><%= link_to Student.find(@medical_issue.student_id).full_name, student_path(@medical_issue.student_id)%></td>
    </tr>
    </tbody>
    </table>
 </div>

<table class="table">
  <tr>
    <td>
<%= link_to 'Edit', edit_medical_issue_path(@medical_issue), class:'btn btn-xs btn-default' %>
<%= link_to 'Back', medical_issues_path, class:'btn btn-xs btn-default' %>
    </td>
  </tr>
</table></center>
<br>