config/routes.rb
LeapsAndBounds::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :student_guardians

  get 'homepage/index'

  resources :report
  get :test, :to => 'reports#subject'

  resources :homepage
  root to: 'homepage#index'

  resources :student_teachers

  resources :teachers

  resources :subject_grade_levels

  resources :student_subject_grade_levels

  resources :teacher_subject_grade_levels

  resources :medical_issues

  resources :sign_in_outs

  resources :emergency_contacts

  resources :guardians

  resources :students

  resources :sign_form

  get 'system_time' => 'application#system_time'

end

app/models/emergency_contact.rb
class EmergencyContact < ActiveRecord::Base
  def full_name
    if self.middle_name == nil
      self.first_name + ' ' + self.last_name
    else
      self.first_name + ' ' + self.middle_name + ' ' + self.last_name
    end
  end

  belongs_to :student

  def self.search(query)
    where("first_name like ? or last_name like ? or primary_phone like ?", "%#{query}%","%#{query}%","%#{query}%")
  end


  #Specifies length constraints
  validates :first_name, :last_name, :relationship, :length =>
      {
          :minimum   => 2,
          :maximum   => 128,
          :too_short => ": %{count} characters is the minimum allowed",
          :too_long  => ": %{count} characters is the minimum allowed"
      }

  validates :primary_phone, :length =>
      {
          :minimum   => 2,
          :maximum   => 20,
          :too_short => ": %{count} characters is the minimum allowed",
          :too_long  => ": %{count} characters is the minimum allowed"
      }

  #Validates associations with other models
  validates_associated :student

end

app/controllers/emergency_contacts_controller.rb
class EmergencyContactsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_emergency_contact, only: [:show, :edit, :update, :destroy]

  # GET /emergency_contacts
  # GET /emergency_contacts.json

  def index
    if params[:search]
      @emergency_contacts = EmergencyContact.search(params[:search]).order("created_at DESC")
    else
      @emergency_contacts = EmergencyContact.page(params[:page]).per(10)
    end
  end

  # GET /emergency_contacts/1
  # GET /emergency_contacts/1.json
  def show
  end

  # GET /emergency_contacts/new
  def new
    @emergency_contact = EmergencyContact.new
  end

  # GET /emergency_contacts/1/edit
  def edit
  end

  # POST /emergency_contacts
  # POST /emergency_contacts.json
  def create
    @emergency_contact = EmergencyContact.new(emergency_contact_params)

    respond_to do |format|
      if @emergency_contact.save
        format.html { redirect_to @emergency_contact, notice: 'Emergency contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @emergency_contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergency_contacts/1
  # PATCH/PUT /emergency_contacts/1.json
  def update
    respond_to do |format|
      if @emergency_contact.update(emergency_contact_params)
        format.html { redirect_to @emergency_contact, notice: 'Emergency contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @emergency_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergency_contacts/1
  # DELETE /emergency_contacts/1.json
  def destroy
    @emergency_contact.destroy
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency_contact
      @emergency_contact = EmergencyContact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_contact_params
      params.require(:emergency_contact).permit(:first_name, :middle_name, :last_name, :relationship, :primary_phone, :secondary_phone, :student_id)
    end
end

app/helpers/emergency_contacts_helper.rb
module EmergencyContactsHelper
end

app/views/emergency_contacts/_form.html.erb
<%= form_for(@emergency_contact) do |f| %>
  <% if @emergency_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emergency_contact.errors.count, "error") %> prohibited this emergency_contact from being saved:</h2>

      <ul>
      <% @emergency_contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship %>
  </div>
  <div class="field">
    <%= f.label :primary_phone %><br>
    <%= f.text_field :primary_phone %>
  </div>
  <div class="field">
    <%= f.label :secondary_phone %><br>
    <%= f.text_field :secondary_phone %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <% if params[:student_id] %>
        <%= f.collection_select(:student_id, Student.all, :id, :full_name, :selected => params[:student_id]) %>
    <% else %>
        <%= f.collection_select(:student_id, Student.all, :id, :full_name) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit "Add", class: 'btn btn-success btn-small' %>
  </div>
<% end %>

app/views/emergency_contacts/edit.html.erb
<h1>Editing emergency_contact</h1>
<center>
<%= render 'form' %>
</center>
<%= link_to 'Show', @emergency_contact %> |
<%= link_to 'Back', emergency_contacts_path %>

app/views/emergency_contacts/index.html.erb
<h1>Emergency Contacts</h1>

<%= form_tag(emergency_contacts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Emergency Contacts" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Relationship</th>
      <th>Phone</th>
      <th>Student</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @emergency_contacts.each do |emergency_contact| %>
      <tr>
        <td><%= link_to emergency_contact.full_name, emergency_contact %></td>
        <td><%= emergency_contact.relationship %></td>
        <td><%= emergency_contact.primary_phone %></td>
        <td><%= Student.find(emergency_contact.student_id).full_name %></td>
        <!--<td><%= link_to 'Show', emergency_contact, class:'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Edit', edit_emergency_contact_path(emergency_contact), class:'btn btn-xs btn-default' %></td>-->
        <td><%= link_to 'Destroy', emergency_contact, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if not params[:search] %>
    <%= will_paginate @emergency_contacts %>
<% end %>

<br>

<center> <table>
  <tr>
    <td>
<%= link_to 'New Contact', new_emergency_contact_path, class:'btn btn-s btn-default' %>
<%= link_to 'Back To Home', homepage_index_path, class:'btn btn-s btn-default' %>
</td>
</tr>
</table></center>

<br>

app/views/emergency_contacts/new.html.erb
<h1>New Emergency Contact</h1>
<center>
<%= render 'form' %>
</center>
<br>
<table class="table">
  <tr>
    <td><br>
      <%= link_to 'Back', request.referer %>
    </td>
  </tr>
</table>

app/views/emergency_contacts/show.html.erb
<h1>Emergency Contact</h1>

<center>
<div class="box">
  <h4 class="select">Student Information</h4>
  <table class="table">
    <thead>
    <th>Full Name:</th>
    <th>Relationship:</th>
    <th>Primary Phone</th>
    <th>Secondary Phone</th>
    <th>Student</th>
    </thead>
    <tbody>
    <tr>
      <td><%= @emergency_contact.full_name %></td>
      <td><%= @emergency_contact.relationship %></td>
      <td><%= @emergency_contact.primary_phone %></td>
      <td><%= @emergency_contact.secondary_phone %></td>
      <td><%= link_to Student.find(@emergency_contact.student_id).full_name, student_path(@emergency_contact.student_id)%></td>
    </tr>
    </tbody>
    </table>
</div>

<table class="table">
  <tr>
    <td>
<%= link_to 'Edit', edit_emergency_contact_path(@emergency_contact), class:'btn btn-xs btn-default' %> |
<%= link_to 'Back', emergency_contacts_path, class:'btn btn-xs btn-default' %>
  </tr>
</table></center>
<br>