config/routes.rb
LeapsAndBounds::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :student_guardians

  get 'homepage/index'

  resources :report
  get :test, :to => 'reports#subject'

  resources :homepage
  root to: 'homepage#index'

  resources :student_teachers

  resources :teachers

  resources :subject_grade_levels

  resources :student_subject_grade_levels

  resources :teacher_subject_grade_levels

  resources :medical_issues

  resources :sign_in_outs

  resources :emergency_contacts

  resources :guardians

  resources :students

  resources :sign_form

  get 'system_time' => 'application#system_time'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :student_teachers, :dependent => :delete_all
  has_many :students, through: :student_teachers
  has_many :teacher_subject_grade_levels, :dependent => :delete_all
  has_many :subject_grade_levels, through: :teacher_subject_grade_levels


  def self.search(query)
    where("first_name like ? or last_name like ?", "%#{query}%","%#{query}%")
  end

  #---Validations area---

  #Checks if the value is either nil or a blank string
  validates :sex, :presence => true

  #Specifies length constraints
  validates :first_name, :last_name, :length =>
      {
          :minimum   => 2,
          :maximum   => 128,
          :too_short => ": %{count} characters is the minimum allowed",
          :too_long  => ": %{count} characters is the minimum allowed"
      }

  #---Methods area---

  #This method combines the first, middle, & last name unless there's no middle name then it's just first & last name
  def full_name
    if self.middle_name == nil
      self.first_name + ' ' + self.last_name
    else
      self.first_name + ' ' + self.middle_name + ' ' + self.last_name
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    if params[:search]
      @teachers = Teacher.search(params[:search]).order("created_at DESC")
    else
      @teachers = Teacher.page(params[:page]).per(10)
    end
  end
  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to request.referer }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:first_name, :middle_name, :last_name, :sex)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, placeholder: "Type in First Name" %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br>
    <%= f.text_field :middle_name, placeholder: "Type in Middle Name (Optional)" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, placeholder: "Type in Last Name" %>
  </div>
  <div class="field">
    <%= f.label :sex %>:</br>
    <%= f.label :sex, "Male", :value=> "Male" %>
    <%= f.radio_button :sex, "Male"%>
    <%= f.label :sex, "Female", :value=> "Female" %>
    <%= f.radio_button :sex, "Female"%>
  </div>
  <div class="actions">
    <%= f.submit "Add", class: 'btn btn-success btn-small' %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>
<center>
<%= render 'form' %>
</center>
<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Teachers</h1>

<%= form_tag(teachers_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Teachers" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Sex</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= link_to teacher.full_name, teacher %></td>
        <td><%= teacher.sex %></td>
        <!--<td><%= link_to 'Show', teacher, class:'btn btn-xs btn-default' %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher), class:'btn btn-xs btn-default'  %></td>-->
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% if not params[:search] %>
    <%= will_paginate @teachers %>
<% end %>
<br>
<center> <table>
  <tr>
    <td>
      <%= link_to 'New Teacher', new_teacher_path, class:'btn btn-s btn-default'  %>
      <%= link_to 'Back To Home', homepage_index_path, class:'btn btn-s btn-default' %>
    </td>
  </tr>
</table></center>
<br>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>
<center>
<%= render 'form' %>
</center>
<table class="table">
  <tr>
    <td><br>
      <%= link_to 'Back', request.referer %>
    </td>
  </tr>
</table>

app/views/teachers/show.html.erb
<div class="box">
  <h4 class="select">Teacher Information</h4>
  <table class="table">
    <thead>
    <th>Name:</th>
    <th>Sex:</th>
    </thead>
    <tbody>
    <tr>
      <td><%= @teacher.full_name %></td>
      <td><%= @teacher.sex %></td>
    </tr>
    </tbody>
  </table>
</div>





<div class="box" style="vertical-align: top">
  <table class="table" style="vertical-align: top">
    <thead>
    <th>Students:</th>
    </thead>
    <tbody>
    <tr>
      <td><% @teacher.student_teachers.each do |st| %>
            <%= link_to st.student.full_name, student_path(st.student_id) %>
            <% if params[:allow_delete] %>
                <%= link_to 'Remove', student_teacher_path(st), :method => :delete, class:'btn btn-xs btn-danger' %>
            <% end %>
            <br><% end %><br>
        <%= link_to 'Add', "/student_teachers/new?teacher_id=#{@teacher.id}", class:'btn btn-xs btn-default' %>
      </td>
    </tr>
    </tbody>
  </table>
</div>

<div class="box" style="vertical-align: top">
  <table class="table" style="vertical-align: top">
    <thead>
    <th>Subject(s):</th>
    </thead>
    <tbody>
    <tr>
      <td><% @teacher.teacher_subject_grade_levels.each do |tgl| %>
            <%= link_to tgl.subject_grade_level.name, subject_grade_levels_path(tgl.id) %>

        <% if params[:allow_delete] %>
            <%= link_to 'Remove', teacher_subject_grade_level_path(tgl), :method => :delete, class:'btn btn-xs btn-danger' %>
        <% end %>
       <br><% end %><br>
        <%= link_to 'Add', "/teacher_subject_grade_levels/new?teacher_id=#{@teacher.id}", class:'btn btn-xs btn-default' %>
      </td>
    </tr>
    </tbody>
  </table>
</div>
<br>
<br>
<center><table class="table">
  <tr>
    <td><center>
      <%= link_to 'Edit', edit_teacher_path(@teacher), class:'btn btn-xs btn-default' %>
      <% if params[:allow_delete] %>
          <%= link_to 'Hide Remove Attributes', '?', class:'btn btn-xs btn-default' %>
      <% else %>
          <%= link_to 'Show Remove Attributes', '?allow_delete=1', class:'btn btn-xs btn-danger' %>
      <% end %>
      <%= link_to 'Back', teachers_path, class:'btn btn-xs btn-default' %></center>
    </td>
  </tr>
</table></center>
<br>